FROM python:3.13-slim

WORKDIR /app

COPY requirements-rembg.txt .
RUN pip install --no-cache-dir -r requirements-rembg.txt

COPY homelib-rembg.py .
ADD https://github.com/danielgatis/rembg/releases/download/v0.0.0/BiRefNet-general-epoch_244.onnx /root/.u2net/birefnet-general.onnx

EXPOSE 7000

CMD ["python", "homelib-rembg.py"]
