FROM python:3.13-slim

WORKDIR /app

COPY requirements-bot.txt .
RUN pip install --no-cache-dir -r requirements-bot.txt

COPY modules ./modules
COPY locales ./locales
COPY homelib-bot.py .

CMD ["python", "homelib-bot.py"]