ARG BASE_IMAGE=homelib-base:latest
FROM ${BASE_IMAGE}

COPY homelib-tg.py .
ADD https://github.com/danielgatis/rembg/releases/download/v0.0.0/BiRefNet-general-epoch_244.onnx /root/.u2net/birefnet-general.onnx

CMD ["python", "homelib-tg.py"]