FROM python:3.13-slim

WORKDIR /app

COPY requirements-tg.txt .
RUN pip install --no-cache-dir -r requirements-tg.txt

COPY modules ./modules
COPY locales ./locales
COPY homelib-tg.py .
ADD https://github.com/danielgatis/rembg/releases/download/v0.0.0/BiRefNet-general-epoch_244.onnx /root/.u2net/birefnet-general.onnx

CMD ["python", "homelib-tg.py"]