name: Build, Push to GHCR and Deploy

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository }}/homelib

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Extract metadata
      id: meta-bot
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_NAME }}-bot
        tags: |
          type=sha,prefix=
          type=ref,event=branch
          latest

    - name: Extract metadata
      id: meta-web
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_NAME }}-web
        tags: |
          type=sha,prefix=
          type=ref,event=branch
          latest

    - name: Extract metadata
      id: meta-rembg
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_NAME }}-rembg
        tags: |
          type=sha,prefix=
          type=ref,event=branch
          latest

    - name: Build and push bot image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./dockerfile-bot
        push: true
        tags: ${{ steps.meta-bot.outputs.tags }}
        labels: ${{ steps.meta-bot.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
          
    - name: Build and push web image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./dockerfile-web
        push: true
        tags: ${{ steps.meta-web.outputs.tags }}
        labels: ${{ steps.meta-web.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push rembg image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./dockerfile-rembg
        push: true
        tags: ${{ steps.meta-rembg.outputs.tags }}
        labels: ${{ steps.meta-rembg.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    needs: [build-and-push]
    runs-on: self-hosted
    permissions:
      contents: read

    steps:
    - name: Deploy to production
      run: |
          # Логинимся в GitHub Container Registry
          echo "${{ secrets.GHCR_TOKEN }}" | docker login -u ${{ github.actor }} --password-stdin ${{ env.REGISTRY }}
          
          # Переходим в директорию с docker-compose.yml
          cd ~/docker

          # Пуллим последний образ
          docker compose pull homelib-tg
          docker compose pull homelib-max
          docker compose pull homelib-web
          docker compose pull homelib-rembg
          
          # Останавливаем и удаляем старый контейнер
          docker compose down homelib-rembg
          docker compose up homelib-rembg -d
          docker compose down homelib-tg
          docker compose up homelib-tg -d
          docker compose down homelib-max
          docker compose up homelib-max -d
          docker compose down homelib-web
          docker compose up homelib-web -d

          # Очищаем старые образы для экономии места
          docker image prune -f